/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_1.h"
#include "SDA_1_aliases.h"
#include "SDA_1.h"
#include "SCL_1_aliases.h"
#include "SCL_1.h"
#include "ACC_1_INT_aliases.h"
#include "ACC_1_INT.h"
#include "ACC_2_INT_aliases.h"
#include "ACC_2_INT.h"
#include "isr_acc_1.h"
#include "isr_acc_2.h"
#include "isr_stream_1.h"
#include "I2C_Master.h"
#include "I2C_Master_PVT.h"
#include "EEPROM.h"
#include "ADC_DelSig.h"
#include "LED_R_aliases.h"
#include "LED_R.h"
#include "LED_B_aliases.h"
#include "LED_B.h"
#include "LED_G_aliases.h"
#include "LED_G.h"
#include "Pin_BAT_aliases.h"
#include "Pin_BAT.h"
#include "Timer_1H.h"
#include "Clock_Counter_1H.h"
#include "isr_Counter_3.h"
#include "Clock_Counter_3.h"
#include "isr_Counter_1H.h"
#include "Timer_3.h"
#include "BUZ_aliases.h"
#include "BUZ.h"
#include "PWM_BUZ.h"
#include "Clock_PWM.h"
#include "Clock_Counter_30.h"
#include "isr_Counter_30.h"
#include "Timer_30.h"
#include "PWM_LED.h"
#include "Clock_PWM_LED.h"
#include "UART_1_IntClock.h"
#include "ADC_DelSig_AMux.h"
#include "ADC_DelSig_Ext_CP_Clk.h"
#include "ADC_DelSig_IRQ.h"
#include "ADC_DelSig_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

